pull_request_rules:
- name: Close all PRs
  conditions:
  -closed
  actions:
    close:
      message: >-
        All issues and pull requests are expected to be created in [gradle-api](https://github.com/remal-gradle-plugins/gradle-api) repository only.
